# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Terraform 0.12.3
      uses: hashicorp/setup-terraform@v1
    - name: 'Terraform : azure init'
      run: terraform init
    - name: 'Terraform : azure plan'
      run: terraform plan -var="client_secret=${{ secrets.clientSecret }}"
    - name: 'Terraform : azure apply'
      run: terraform apply -auto-approve -var="client_secret=${{ secrets.clientSecret }}"
