# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - # ""Note: 'AZURE_SP' secret is required to be setup and added into GitHub Secrets: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets""
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - run: |
        $secrets = "${{ secrets.AZURE_SP }}"
        #$secrets = $secrets -replace "`n",", " -replace "`r",", "
        $secretsObj = ($secrets | ConvertFrom-Json)
        $secretsObj
        Write-Host "Sub: " $secretsObj.subscriptionId
    - name: Install Terraform 0.12.3
      uses: hashicorp/setup-terraform@v1
    - name: 'Terraform : azure init'
      run: terraform init
    - name: 'Terraform : azure plan'
      run: terraform plan -var-file=""terraform.tfvars""
    - name: 'Terraform : azure validate and apply'
      run: terraform apply -var-file=""terraform.tfvars""
